[tox]
envlist = py
isolated_build = true

[testenv]
package = wheel
deps =
    pytest
    pytest-cov
commands =
    pytest {tty:--color=yes} {posargs:--cov-report=html:{envtmpdir}/htmlcov/} \
        --cov=ci_patterns_demo --cov-report=term-missing

[testenv:pre-commit]
skip_install = true
deps = pre-commit
pass_env =
    {[testenv]pass_env}
    SKIP
commands = pre-commit run --all-files --show-diff-on-failure
